# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-21 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=70)),
                ('location', models.SlugField(max_length=100)),
                ('time', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilapp.Services')),
            ],
        ),
    ]
