# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-21 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilapp', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='companyprofile',
        ),
    ]
